name: Update docs
on: workflow_dispatch

jobs:
    get-tags:
      runs-on: ubuntu-latest
      steps:
        - uses: octokit/request-action@v2.x
          id: get_latest_release
          with:
            route: GET /repos/diogofgm/TA-aruba_networks/git/matching-refs/tags
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"